# 1. Import the NumPy package under the name np

In [5]:
import numpy as np

# 2. Print the NumPy version and the configuration

In [6]:
print(np.__version__)
np.show_config()

1.22.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dylan/Desktop/heart-disease/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dylan/Desktop/heart-disease/env\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dylan/Desktop/heart-disease/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dylan/Desktop/heart-disease/env\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dylan/Desktop/heart-disease/env\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/dylan/Desktop/heart-disease/env\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/dylan/Desktop/heart-disease/env\\Library\\lib

# 3. Create a null vector of size 10

In [7]:
Z = np.zeros(10)
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 4. How to find the memory size of any array

In [8]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# 5. How to get the documentation of the NumPy add function from the command line?

In [14]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

# 6. Create a null vector of size 10 but the fifth value which is 1

In [17]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [22]:
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


# 7. Create a vector with values ranging from 10 to 49

In [20]:
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


# 8. Reverse a vector (first element becomes last)

In [23]:
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


# 9. Create a 3x3 matrix with values ranging from 0 to 8

In [24]:
Z = np.arange(9).reshape(3, 3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [25]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int64),)


# 11. Create a 3x3 identity matrix

In [26]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 12. Create a 3x3x3 array with random values

In [27]:
Z = np.random.random((3,3,3))
print(Z)

[[[0.32045706 0.39655961 0.25880107]
  [0.86195333 0.95679319 0.62398567]
  [0.35657782 0.71014191 0.36092115]]

 [[0.61943469 0.86021985 0.7157808 ]
  [0.59831269 0.01371193 0.31079167]
  [0.58655374 0.90211942 0.17534957]]

 [[0.44787893 0.76484296 0.52694259]
  [0.78436356 0.88485456 0.25277527]
  [0.8707703  0.10989178 0.69354736]]]


# 13. Create a 10x10 array with random values and find the minimum and maximum values

In [28]:
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.002045266863275108 0.9791112325909384


# 14. Create a random vector of size 30 and find the mean value

In [29]:
Z = np.random.random(30)
m = Z.mean()
print(m)

0.44651957797402303


# 15. Create a 2d array with 1 on the border and 0 inside

In [30]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# 16. How to add a border (filled with 0's) around an existing array?

In [31]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


# 17. What is the result of the following expression?

In [32]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [33]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


# 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [35]:
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [37]:
Z = np.diag(1+np.arange(4),k=0)
print(Z)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [39]:
Z = np.diag(1+np.arange(4),k=1)
print(Z)

[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


In [42]:
Z = np.zeros((8,8), dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


###### Alternative solution: Using reshaping

In [43]:
arr = np.ones(64,dtype=int)
arr[::2]=0
arr = arr.reshape((8,8))
print(arr)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


# 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [44]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


# 21. Create a checkerboard 8x8 matrix using the title function

In [48]:
Z = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 22. Normalize a 5x5 random matrix

In [49]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-0.9658838   0.32156692  0.7475135  -1.18137664 -1.17790823]
 [-0.1914222  -1.26377219  0.58986748 -0.42354602  1.00473362]
 [ 0.21686957  1.4753894   0.88808758 -0.89680707  1.57929754]
 [-0.93076955 -0.61175895 -0.65490801 -1.04921454 -0.66276503]
 [ 1.56870126  0.29721032  1.15209285  1.50565315 -1.33685097]]


# 23. Create a custon dtype that decscribes a color as four unsigned bytes (RGBA)

In [50]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [53]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


###### Alternative solution, in Python 3.5 and above

In [54]:
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 25. Given a 1D array, negate all elements which are between 3 and 8, in place

In [55]:
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# 26. What is the output of the following script?

In [56]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


# 27. Consider an integer vector Z, which of these expressions are legal?

In [57]:
Z**Z
Z << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

ValueError: Integers to negative integer powers are not allowed.

# 28. What are the results of the following expressions?

In [60]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\548293649.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-2.14748365e+09])

In [61]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


# 29. How to round away from zero a float array?

In [62]:
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-6. -3.  4. -8.  9. -8.  2. 10.  2.  2.]


In [63]:
# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[-6. -3.  4. -8.  9. -8.  2. 10.  2.  2.]


# 30. How to find common values between two arrays?

In [64]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[0 4 6 7 8]


# 31. How to ignore all numpy warnings (not recommended)?

In [65]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [69]:
_ = np.seterr(**defaults)

In [68]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

# 32. Is the following expression true?

In [70]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

# 33. How to get the dates of yesterday, today, and tomorrow?

In [76]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)

# 34.How to get all the dates corresponding to the month of July 2016?

In [77]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

In [79]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

# 36. Extract the integer part of a random array of positive numbers using 4 different methods

In [80]:
Z = np.random.uniform(0,10,10)

print(Z -Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 9. 3. 2. 7. 9. 1. 0. 9. 8.]
[0. 9. 3. 2. 7. 9. 1. 0. 9. 8.]
[0. 9. 3. 2. 7. 9. 1. 0. 9. 8.]
[0 9 3 2 7 9 1 0 9 8]
[0. 9. 3. 2. 7. 9. 1. 0. 9. 8.]


# 37. Create a 5x5 matrix with row values ranging from 0 to 4

In [82]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [83]:
# without broadcasting
Z = np.tile(np.arange(0, 5), (5, 1))
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 38. Consider a generator function that generates 10 integers and use it to build an array

In [84]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [85]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 40. Create a random vector of size 10 and sort it

In [86]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.09535533 0.13719867 0.19605826 0.20571895 0.31622368 0.35037431
 0.39761105 0.46447478 0.55102337 0.62803644]


# 41. How to sum a small array faster than np.sum?

In [87]:
# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)

45

# 42. Consider two random arrays (A and B), check if they are equal

In [88]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

In [94]:
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

False


In [95]:
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,A)
print(equal)

True


In [96]:
# 43. Make an array immutable (read-only)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert then to polar coordinates

In [98]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.50628642 0.99903616 0.48185957 0.58066336 0.86845219 1.20445004
 0.45476297 0.79211108 0.33657833 0.97969674]
[0.67660633 1.21504534 0.1736659  0.50265791 1.40128434 0.7351955
 0.82877535 1.56788508 0.93460143 0.0772618 ]


# 45. Create a random vector of size 10 and replace the maximum value by 0

In [112]:
Z = np.random.random(10)
print(Z)
print("Before ⬆️")
print("")
print("After ⬇️")
Z[Z.argmax()] = 0
print(Z)

[0.78273884 0.63635364 0.75409687 0.20299848 0.35574616 0.80244374
 0.01949232 0.27832546 0.81396799 0.50092968]
Before ⬆️

After ⬇️
[0.78273884 0.63635364 0.75409687 0.20299848 0.35574616 0.80244374
 0.01949232 0.27832546 0.         0.50092968]


# 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

In [114]:
Z = np.zeros((5,5), [('x', float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [115]:
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


# 48. Print the minimum and maximum representable value for each numpy scalar type

In [117]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 49. How to print all the values of an array?

In [116]:
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# 50. How to find the closest value (to a given scalar) in a vector?

In [119]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

3


# 51. Create a structured array representing a position (x,y) and a color (r,g,b)

In [121]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                   ('color',     [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\4199653329.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances

In [123]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.94615809 0.67010947 0.50487648 0.33925672 0.72823027
  0.54247158 0.73544512 0.81474223 0.91301167]
 [0.94615809 0.         0.72889506 0.54349331 0.71027322 0.271894
  0.80638304 0.25706477 0.13170408 0.20543588]
 [0.67010947 0.72889506 0.         0.28954471 0.34581865 0.46866139
  0.98653209 0.70771155 0.64895379 0.84878263]
 [0.50487648 0.54349331 0.28954471 0.         0.1851324  0.27556888
  0.70710256 0.44731488 0.43171008 0.61044223]
 [0.33925672 0.71027322 0.34581865 0.1851324  0.         0.45194597
  0.67074193 0.56829329 0.58883899 0.74492558]
 [0.72823027 0.271894   0.46866139 0.27556888 0.45194597 0.
  0.74065508 0.27144047 0.18054929 0.38325925]
 [0.54247158 0.80638304 0.98653209 0.70710256 0.67074193 0.74065508
  0.         0.5505956  0.69735422 0.66115943]
 [0.73544512 0.25706477 0.70771155 0.44731488 0.56829329 0.27144047
  0.5505956  0.         0.15141633 0.18084269]
 [0.81474223 0.13170408 0.64895379 0.43171008 0.58883899 0.18054929
  0.69735422 0.1514163

In [124]:
# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

In [125]:
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.29344601 0.58144899 0.53018334 0.74710815 0.66236764
  0.63491014 0.43417627 0.77258408 0.35197779]
 [0.29344601 0.         0.29761233 0.45179224 0.63814981 0.36906074
  0.74045412 0.63094235 0.59679452 0.47244828]
 [0.58144899 0.29761233 0.         0.45430179 0.54965    0.12747041
  0.85113152 0.82905073 0.43060294 0.64330062]
 [0.53018334 0.45179224 0.45430179 0.         0.21727091 0.58142261
  0.41715172 0.49350193 0.29136678 0.31668318]
 [0.74710815 0.63814981 0.54965    0.21727091 0.         0.66546803
  0.50451934 0.66271868 0.17904517 0.50862137]
 [0.66236764 0.36906074 0.12747041 0.58142261 0.66546803 0.
  0.97775878 0.94567332 0.53083023 0.76271376]
 [0.63491014 0.74045412 0.85113152 0.41715172 0.50451934 0.97775878
  0.         0.27036608 0.66382441 0.28648355]
 [0.43417627 0.63094235 0.82905073 0.49350193 0.66271868 0.94567332
  0.27036608 0.         0.78290327 0.19002764]
 [0.77258408 0.59679452 0.43060294 0.29136678 0.17904517 0.53083023
  0.66382441 0.78290

# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [126]:
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & ubuntu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[96 18  9 58 87 14 36 59 76 60]


# 54. How to read the following file?

In [128]:
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11

SyntaxError: invalid syntax (2460604331.py, line 2)

In [134]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5,
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\926431699.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


ValueError: Some errors were detected !
    Line #2 (got 5 columns instead of 6)
    Line #3 (got 5 columns instead of 6)

# 55. What is the equivalent of enumerate for numpy arrays?

In [135]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


# 56. Generate a generic 2D Gaussian-like array

In [138]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

# 57. How to randomly place p elements in a 2D array?

In [139]:
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n, n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


# 58. Subtract the mean of each row of a matrix

In [141]:
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[ 0.07186446  0.1560981  -0.22887979 -0.24285984 -0.01376861 -0.17830218
  -0.09233262  0.05071591  0.47820175 -0.00073717]
 [-0.01191811 -0.13554238  0.56624755 -0.20457369  0.17767567  0.14782926
   0.17207929  0.09614548 -0.38535623 -0.42258684]
 [-0.09304401  0.10108709 -0.32492542  0.19366772 -0.5043329   0.43573951
   0.24452897  0.07009081 -0.2951076   0.17229582]
 [ 0.34349399  0.12510237 -0.03454462  0.1302366  -0.08520993 -0.41948403
  -0.51251033  0.26467036  0.00310656  0.18513903]
 [-0.23183458 -0.01752065  0.20117684 -0.07009646  0.3437544  -0.13041133
   0.03994617  0.32794842 -0.54340648  0.08044368]]


# 59. How to sort an array by the nth column?

In [142]:
# Author: Steve Tjoa

Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[6 4 8]
 [8 7 5]
 [5 9 9]]
[[6 4 8]
 [8 7 5]
 [5 9 9]]


# 60. How to tell if a given 2D array has null columns?

In [145]:
# Author: Warren Weckesser

# null : 0
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))

True
[False False  True]


# 61. Find the nearest value from a given value in an array

In [146]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.48135118555771506


# 62. Considering two arrays with shape (1,3) and (3,1) | Compute their sum using an iterator

In [147]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# 63. Create an array class that has a name attribute

In [149]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [150]:
# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[2. 4. 3. 4. 3. 2. 5. 1. 2. 4.]
[3. 7. 5. 7. 5. 3. 9. 1. 3. 7.]


# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?

In [151]:
# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


# 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors

In [152]:
# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


# 67. Considering a four dimensions array | Get sum over the last two axis at once

In [153]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[41 49 40 57]
 [51 41 53 48]
 [61 65 51 57]]
[[41 49 40 57]
 [51 41 53 48]
 [61 65 51 57]]


# 68. Considering a one-dimensional vector D | Compute means of subsets of D using a vector S of same size describing subset indices

In [155]:
# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


[0.50659827 0.43170305 0.58522643 0.57386968 0.45729133 0.45131958
 0.38939303 0.49897286 0.64218727 0.5289982 ]
0    0.506598
1    0.431703
2    0.585226
3    0.573870
4    0.457291
5    0.451320
6    0.389393
7    0.498973
8    0.642187
9    0.528998
dtype: float64


# 69. How to get the diagonal of a bot product?

In [156]:
# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.einsum("ij,ji->i", A, B)

array([1.83189282, 0.82379401, 1.0370563 , 1.09825358, 0.87739227])

# 70. Consider the vector [1, 2, 3, 4, 5] | Build a new vector with 3 consecutive zeros interleaved between each value

In [157]:
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


# 71. Consider an array of dimension (5,5,3) | Multiply it by an array with dimensions (5,5)

In [158]:
A = np.ones((5,5,3))
B = 2*np.ones((5, 5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


# 72. Swap two rows of an array

In [160]:
# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


# 73. Consider a set of 10 triplets describing triangles (with shared vertices) | Find the set of unique line segments composing all the triangles

In [162]:
# Author: Nicholas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1' ,F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 30) ( 1, 49) ( 4, 86) ( 4, 91) ( 8, 24) ( 8, 42) ( 8, 74) ( 8, 88)
 (14, 29) (14, 75) (15, 41) (15, 99) (24, 33) (24, 42) (24, 81) (26, 36)
 (26, 66) (27, 51) (27, 80) (29, 75) (30, 49) (33, 81) (36, 66) (38, 92)
 (38, 93) (41, 99) (51, 80) (74, 88) (86, 91) (92, 93)]


# 74. Given a sorted array C that corresponds to a bincount | Produce an array A such that np.bincount(A) == C?

In [163]:
# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


# 75. How to compute averages using a sliding window over an array?

In [164]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure you NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


# 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]))

In [166]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff19999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


# 77. How to negate a boolean, or to change the sign of a float inplace?

In [167]:
# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.88041478, -0.88037179,  0.92239755,  0.26277304,  0.04801425,
       -0.0958247 , -0.71862151, -0.57768237,  0.89422419, -0.0329564 ,
        0.41159437, -0.04371569,  0.86471558,  0.23888324,  0.00928317,
       -0.76329963,  0.43587459, -0.19521154,  0.75851058,  0.19469828,
       -0.26529005, -0.76455545, -0.31156418,  0.32854155, -0.49558415,
       -0.23883033,  0.07721148, -0.69787185, -0.01363163,  0.60486142,
       -0.31039884,  0.80157887,  0.43778552,  0.10623583,  0.66643916,
       -0.96924457, -0.75336212,  0.09098763,  0.81622086, -0.7728083 ,
       -0.16627679,  0.50661925,  0.17675008,  0.72838775,  0.321557  ,
       -0.96541464, -0.32687498,  0.39902935, -0.43262895, -0.75265858,
        0.07134811,  0.07535889,  0.71156625,  0.92778083, -0.36894475,
       -0.09656611, -0.40895064, -0.8955434 ,  0.22011137, -0.1716527 ,
        0.98864682, -0.6702852 ,  0.52364845,  0.54982688, -0.84230031,
        0.88099313,  0.80716186, -0.1270505 , -0.76400426, -0.51

# 78. Consider 2 sets of points P0,P1 descibing lines (2d) and a point p | Compute distance from p to each line 1 (P0[i],P1[i])?

In [175]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 6.20897634  9.92985934 14.93298925  4.40339831 13.37802985 11.92256607
  3.10151772 12.16342501 10.51393036 15.99261124]


# 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P | Compute the distance from each point j (P[j]) to each line i (P0[i],P1[i])

In [177]:
# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 4.54219359  2.1440773   4.0496575   4.68628332  8.42138193 11.19377971
   3.18246383  1.63729733  2.84474311  9.29423586]
 [ 2.60849257  4.54561605  4.23528849  7.02354849  1.77352021  6.22205816
   4.55505794  1.7893501   1.75075028  3.9284479 ]
 [ 6.10388625  2.54128279  6.40041602  2.84626145 11.15651639 11.75825472
   5.08535819  0.41476428  4.34363793 10.02199346]
 [10.18879016  3.63976852 12.58422957  2.05252349 18.3936478  13.20108056
  10.07649714  2.85980495  8.34564578 11.89690246]
 [ 0.0451276   4.47071424  0.68129551  4.97864286  5.37707243  7.60533687
   1.49498352  0.67958523  3.27263606  5.52635487]
 [ 7.67529478 13.77943621  5.68188843  2.18563113  7.54985726  1.56117743
   8.29671755  7.82213875 11.27211258  3.50297212]
 [ 5.65484513 18.20976661  0.34030686 10.21573663 16.54123548  3.04613474
   4.92960013 14.45744474 18.56514316  4.44856294]
 [ 3.27607493 10.06109805  1.90100084  0.39104226  8.51981274  2.76500768
   4.05441577  5.02413857  8.88185549  0.87790945]


# 80. Consider an arbitray array | Write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` when necessary)

In [179]:
# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 2 2 5 2 8 0 2 9 8]
 [0 4 3 2 7 5 7 2 9 5]
 [3 3 4 7 9 2 4 9 8 3]
 [6 6 2 3 3 1 4 1 8 5]
 [4 8 4 3 0 8 5 0 9 7]
 [2 2 2 2 5 5 7 7 4 6]
 [0 4 6 4 5 8 7 5 2 2]
 [0 5 0 0 6 9 6 0 6 6]
 [6 8 7 0 4 5 1 5 7 8]
 [9 8 0 8 2 6 1 7 2 4]]
[[0 0 0 0 0]
 [0 5 2 2 5]
 [0 0 4 3 2]
 [0 3 3 4 7]
 [0 6 6 2 3]]


C:\Users\dylan\AppData\Local\Temp\ipykernel_11484\764741246.py:25: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


# 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] | Generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]

In [180]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


# 82. Compute a matrix rank

In [184]:
# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


# 83. How to find the most frequeny value in an array?

In [185]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

6


# 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix

In [186]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[3 4 1]
   [1 0 3]
   [1 0 1]]

  [[4 1 3]
   [0 3 1]
   [0 1 2]]

  [[1 3 4]
   [3 1 2]
   [1 2 4]]

  [[3 4 2]
   [1 2 0]
   [2 4 0]]

  [[4 2 0]
   [2 0 3]
   [4 0 4]]

  [[2 0 3]
   [0 3 2]
   [0 4 0]]

  [[0 3 2]
   [3 2 1]
   [4 0 0]]

  [[3 2 1]
   [2 1 2]
   [0 0 3]]]


 [[[1 0 3]
   [1 0 1]
   [4 0 2]]

  [[0 3 1]
   [0 1 2]
   [0 2 4]]

  [[3 1 2]
   [1 2 4]
   [2 4 2]]

  [[1 2 0]
   [2 4 0]
   [4 2 1]]

  [[2 0 3]
   [4 0 4]
   [2 1 0]]

  [[0 3 2]
   [0 4 0]
   [1 0 2]]

  [[3 2 1]
   [4 0 0]
   [0 2 4]]

  [[2 1 2]
   [0 0 3]
   [2 4 3]]]


 [[[1 0 1]
   [4 0 2]
   [4 2 4]]

  [[0 1 2]
   [0 2 4]
   [2 4 2]]

  [[1 2 4]
   [2 4 2]
   [4 2 2]]

  [[2 4 0]
   [4 2 1]
   [2 2 0]]

  [[4 0 4]
   [2 1 0]
   [2 0 4]]

  [[0 4 0]
   [1 0 2]
   [0 4 3]]

  [[4 0 0]
   [0 2 4]
   [4 3 4]]

  [[0 0 3]
   [2 4 3]
   [3 4 2]]]


 [[[4 0 2]
   [4 2 4]
   [3 3 2]]

  [[0 2 4]
   [2 4 2]
   [3 2 1]]

  [[2 4 2]
   [4 2 2]
   [2 1 0]]

  [[4 2 1]
   [2 2 0]
   [1 0 3]]

  [[2 1 0]
   

# 85. Create a 2D array subclass such that Z[i,j] == Z[j,i]

In [187]:
# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem_(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)
        
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 8 13  2 12  9]
 [13  5  4 10  7]
 [ 2  4  8 42 12]
 [12 10 12  7  9]
 [ 9  7 12  9  1]]


# 86. Consider a set of p matrices with shape (n,n) and a set of a p vectors with shape (n,1) | Compute the sum of the p matrix products at once (result has shape (n,1))

In [188]:
# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


# 87. Consider a 16x16 array | Get the block-sum (block size is 4x4)

In [189]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

# Author: Jeff Luo (@Jeff1999)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


# 88. How to implement the Game of Life using numpy arrays?

In [190]:
# Author: Nicolas Rougier

def iterate(Z):
    #Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    
    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 1 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 1 1 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
  0 0 0 1 1 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

# 89. How to get the n largest values of an array

In [191]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argpartition(-Z,n)[:n]])

[9999 9998 9997 9996 9995]


# 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item)

In [192]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)
    
    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
        
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


# 91. How to create a record array from a regular array

In [193]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names = 'col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


# 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods

In [194]:
# Author: Ryan G.

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.67 s ± 43.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
362 ms ± 48.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
196 ms ± 7.82 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 93. Consider two arrays A and B of shape (8,3) and (2,2). Find rows of A that contain elements of each row of B regardless of the order of the elements in B

In [195]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[4 6]


# 94. Considering a 10x3 matrix, extract rows with unequal values (e.g., [2,2,3])

In [196]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# solution for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 3 3]
 [3 0 1]
 [2 2 1]
 [1 3 4]
 [0 1 2]
 [0 1 1]
 [3 4 4]
 [3 4 2]
 [2 4 3]
 [2 2 3]]
[[4 3 3]
 [3 0 1]
 [2 2 1]
 [1 3 4]
 [0 1 2]
 [0 1 1]
 [3 4 4]
 [3 4 2]
 [2 4 3]
 [2 2 3]]
[[4 3 3]
 [3 0 1]
 [2 2 1]
 [1 3 4]
 [0 1 2]
 [0 1 1]
 [3 4 4]
 [3 4 2]
 [2 4 3]
 [2 2 3]]


# 95. Convert a vector of ints into a matrix binary representation

In [197]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


# 96. Given a two dimensional array | Extract unique rows

In [198]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 1 1]]
[[0 1 0]
 [0 1 1]
 [1 1 1]]


# 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function

In [199]:
# Author: ALex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.47423684, 0.14861618, 0.35077531, 0.36958824, 0.47361369,
        0.60704264, 0.66796545, 0.30254992, 0.20767287, 0.29425099],
       [0.51305369, 0.16078059, 0.37948668, 0.39983948, 0.51237954,
        0.6567298 , 0.72263922, 0.32731399, 0.22467114, 0.31833579],
       [0.16686385, 0.05229174, 0.12342297, 0.13004244, 0.16664459,
        0.21359258, 0.23502874, 0.1064545 , 0.07307128, 0.10353446],
       [0.38072971, 0.11931294, 0.28161157, 0.29671508, 0.38022943,
        0.48734967, 0.53626009, 0.24289497, 0.1667252 , 0.23623237],
       [0.18402514, 0.05766973, 0.13611653, 0.14341679, 0.18378333,
        0.23555973, 0.25920051, 0.11740292, 0.08058638, 0.11418257],
       [0.49892521, 0.15635301, 0.36903637, 0.38882869, 0.49826962,
        0.63864477, 0.70273917, 0.31830041, 0.21848414, 0.30956945],
       [0.2784662 , 0.08726564, 0.20597107, 0.21701779, 0.2781003 ,
        0.35644818, 0.39222132, 0.17765369, 0.12194303, 0.17278066],
       [0.23381341, 0.07327237, 0.1729430

# 98. Considering a path described by two vectors (X,Y) | Sample it using equidistant samples

In [201]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

# 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n

In [202]:
# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
               [2.0, 0.0, 1.0, 1.0],
               [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


# 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means)

In [203]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.17236365  0.25673201]
